CXX			:= g++
CXX_FLAGS 	:= --std=c++11

BIN			:= bin
SRC			:= src
INCLUDES	:= -Iincludes

ifeq ($(UNAME), Darwin)

else

LIB			:= libs
LIBRARIES	:= -lglfw3 -lgdi32

endif

EXECUTABLE	:= main


build: $(SRC)/*.cpp $(SRC)/*.c
	$(CXX) $(CXX_FLAGS) $(INCLUDES) -L$(LIB) $^ -o engine $(LIBRARIES)
